# Generated by Django 3.2.5 on 2024-02-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
