# Generated by Django 3.2.5 on 2024-02-05 17:39

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.IntegerField(blank=True, null=True, validators=[user.models.validate_allowed_roles]),
        ),
    ]
