# Generated by Django 3.2.5 on 2024-02-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_role_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'required': 'Ez a mező kötelező.', 'unique': 'Már létezik felhasználó a megadott felhasználónévvel.'}, max_length=16, unique=True),
        ),
    ]
