# Generated by Django 3.2.5 on 2024-02-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'required': 'Ez a mező kötelező.', 'unique': 'Már létezik felhasználó a megadott email címmel.'}, max_length=50, null=True, unique=True),
        ),
    ]
