# Generated by Django 3.2.5 on 2024-02-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'required': 'Ez a mező kötelező.'}, max_length=50, null=True),
        ),
    ]
