# Generated by Django 3.2.5 on 2024-02-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20240217_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username_change_count',
            field=models.IntegerField(default=0),
        ),
    ]
