# Generated by Django 3.2.5 on 2024-02-22 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_user_username_change_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangedUsername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_username', models.CharField(error_messages={'required': 'Ez a mező kötelező.'}, max_length=140)),
                ('time_of_change', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
