# Generated by Django 3.2.5 on 2024-02-22 11:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_changedusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changedusername',
            name='time_of_change',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 11, 33, 44, 649289, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changedusername',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
