# Generated by Django 3.2.5 on 2024-02-22 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_auto_20240222_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changedusername',
            name='time_of_change',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 11, 34, 41, 299530, tzinfo=utc)),
        ),
    ]
