# Generated by Django 3.2.5 on 2024-02-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='isDefault',
            new_name='is_default',
        ),
    ]
