# Generated by Django 3.2.5 on 2024-03-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_user_address_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='is_default',
            new_name='default',
        ),
    ]
